env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - eslint:recommended
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  import/extensions: 1

